language_list = [
    {
        "country": "Australia",
        "language": "English",
        "discord_emoji": ":flag_au:",
        "language_code": "en-AU",
    },
    {
        "country": "Belgium",
        "language": "Dutch",
        "discord_emoji": ":flag_be:",
        "language_code": "nl-BE",
    },
    {
        "country": "Brazil",
        "language": "Portuguese",
        "discord_emoji": ":flag_br:",
        "language_code": "pt-BR",
    },
    {
        "country": "Bulgaria",
        "language": "Bulgarian",
        "discord_emoji": ":flag_bg:",
        "language_code": "bg-BG",
    },
    {
        "country": "Canada",
        "language": "French",
        "discord_emoji": ":flag_ca:",
        "language_code": "fr-CA",
    },
    {
        "country": "China",
        "language": "Mandarin Chinese",
        "discord_emoji": ":flag_cn:",
        "language_code": "cmn-CN",
    },
    {
        "country": "Czech Republic",
        "language": "Czech",
        "discord_emoji": ":flag_cz:",
        "language_code": "cs-CZ",
    },
    {
        "country": "Denmark",
        "language": "Danish",
        "discord_emoji": ":flag_dk:",
        "language_code": "da-DK",
    },
    {
        "country": "Finland",
        "language": "Finnish",
        "discord_emoji": ":flag_fi:",
        "language_code": "fi-FI",
    },
    {
        "country": "France",
        "language": "French",
        "discord_emoji": ":flag_fr:",
        "language_code": "fr-FR",
    },
    {
        "country": "Germany",
        "language": "German",
        "discord_emoji": ":flag_de:",
        "language_code": "de-DE",
    },
    {
        "country": "Greece",
        "language": "Greek",
        "discord_emoji": ":flag_gr:",
        "language_code": "el-GR",
    },
    {
        "country": "Hong Kong",
        "language": "Chinese",
        "discord_emoji": ":flag_hk:",
        "language_code": "yue-HK",
    },
    {
        "country": "Hungary",
        "language": "Hungarian",
        "discord_emoji": ":flag_hu:",
        "language_code": "hu-HU",
    },
    {
        "country": "Iceland",
        "language": "Icelandic",
        "discord_emoji": ":flag_is:",
        "language_code": "is-IS",
    },
    {
        "country": "India",
        "language": "Bengali",
        "discord_emoji": ":flag_in:",
        "language_code": "bn-IN",
    },
    {
        "country": "India",
        "language": "English",
        "discord_emoji": ":flag_in:",
        "language_code": "en-IN",
    },
    {
        "country": "India",
        "language": "Gujarati",
        "discord_emoji": ":flag_in:",
        "language_code": "gu-IN",
    },
    {
        "country": "India",
        "language": "Hindi",
        "discord_emoji": ":flag_in:",
        "language_code": "hi-IN",
    },
    {
        "country": "India",
        "language": "Kannada",
        "discord_emoji": ":flag_in:",
        "language_code": "kn-IN",
    },
    {
        "country": "India",
        "language": "Malayalam",
        "discord_emoji": ":flag_in:",
        "language_code": "ml-IN",
    },
    {
        "country": "India",
        "language": "Tamil",
        "discord_emoji": ":flag_in:",
        "language_code": "ta-IN",
    },
    {
        "country": "India",
        "language": "Telugu",
        "discord_emoji": ":flag_in:",
        "language_code": "te-IN",
    },
    {
        "country": "Indonesia",
        "language": "Indonesian",
        "discord_emoji": ":flag_id:",
        "language_code": "id-ID",
    },
    {
        "country": "Italy",
        "language": "Italian",
        "discord_emoji": ":flag_it:",
        "language_code": "it-IT",
    },
    {
        "country": "Japan",
        "language": "Japanese",
        "discord_emoji": ":flag_jp:",
        "language_code": "ja-JP",
    },
    {
        "country": "Latvia",
        "language": "Latvian",
        "discord_emoji": ":flag_lv:",
        "language_code": "lv-LV",
    },
    {
        "country": "Malaysia",
        "language": "Malay",
        "discord_emoji": ":flag_my:",
        "language_code": "ms-MY",
    },
    {
        "country": "Netherlands",
        "language": "Dutch",
        "discord_emoji": ":flag_nl:",
        "language_code": "nl-NL",
    },
    {
        "country": "Norway",
        "language": "Norwegian",
        "discord_emoji": ":flag_no:",
        "language_code": "nb-NO",
    },
    {
        "country": "Philippines",
        "language": "Filipino",
        "discord_emoji": ":flag_ph:",
        "language_code": "fil-PH",
    },
    {
        "country": "Poland",
        "language": "Polish",
        "discord_emoji": ":flag_pl:",
        "language_code": "pl-PL",
    },
    {
        "country": "Portugal",
        "language": "Portuguese",
        "discord_emoji": ":flag_pt:",
        "language_code": "pt-PT",
    },
    {
        "country": "Romania",
        "language": "Romanian",
        "discord_emoji": ":flag_ro:",
        "language_code": "ro-RO",
    },
    {
        "country": "Russia",
        "language": "Russian",
        "discord_emoji": ":flag_ru:",
        "language_code": "ru-RU",
    },
    {
        "country": "Saudi Arabia",
        "language": "Arabic",
        "discord_emoji": ":flag_sa:",
        "language_code": "ar-XA",
    },
    {
        "country": "Serbia",
        "language": "Serbian",
        "discord_emoji": ":flag_rs:",
        "language_code": "sr-RS",
    },
    {
        "country": "Slovakia",
        "language": "Slovak",
        "discord_emoji": ":flag_sk:",
        "language_code": "sk-SK",
    },
    {
        "country": "South Africa",
        "language": "Afrikaans",
        "discord_emoji": ":flag_za:",
        "language_code": "af-ZA",
    },
    {
        "country": "South Korea",
        "language": "Korean",
        "discord_emoji": ":flag_kr:",
        "language_code": "ko-KR",
    },
    {
        "country": "Spain",
        "language": "Catalan",
        "discord_emoji": ":flag_es:",
        "language_code": "ca-ES",
    },
    {
        "country": "Spain",
        "language": "Spanish",
        "discord_emoji": ":flag_es:",
        "language_code": "es-ES",
    },
    {
        "country": "Sweden",
        "language": "Swedish",
        "discord_emoji": ":flag_se:",
        "language_code": "sv-SE",
    },
    {
        "country": "Thailand",
        "language": "Thai",
        "discord_emoji": ":flag_th:",
        "language_code": "th-TH",
    },
    {
        "country": "Turkey",
        "language": "Turkish",
        "discord_emoji": ":flag_tr:",
        "language_code": "tr-TR",
    },
    {
        "country": "Ukraine",
        "language": "Ukrainian",
        "discord_emoji": ":flag_ua:",
        "language_code": "uk-UA",
    },
    {
        "country": "United Kingdom",
        "language": "English",
        "discord_emoji": ":flag_gb:",
        "language_code": "en-GB",
    },
    {
        "country": "United States",
        "language": "English",
        "discord_emoji": ":flag_us:",
        "language_code": "en-US",
    },
    {
        "country": "United States",
        "language": "Spanish",
        "discord_emoji": ":flag_us:",
        "language_code": "es-US",
    },
    {
        "country": "Vietnam",
        "language": "Vietnamese ",
        "discord_emoji": ":flag_vn:",
        "language_code": "vi-VN",
    },
]

language_voice_tree = {
    "af-ZA": ["af-ZA-Standard-A"],
    "ar-XA": [
        "ar-XA-Wavenet-A",
        "ar-XA-Wavenet-B",
        "ar-XA-Wavenet-C",
        "ar-XA-Wavenet-D",
        "ar-XA-Standard-A",
        "ar-XA-Standard-B",
        "ar-XA-Standard-C",
        "ar-XA-Standard-D",
    ],
    "bg-BG": ["bg-bg-Standard-A"],
    "bn-IN": [
        "bn-IN-Wavenet-A",
        "bn-IN-Wavenet-B",
        "bn-IN-Standard-A",
        "bn-IN-Standard-B",
    ],
    "ca-ES": ["ca-es-Standard-A"],
    "cmn-CN": [
        "cmn-CN-Wavenet-A",
        "cmn-CN-Wavenet-B",
        "cmn-CN-Wavenet-C",
        "cmn-CN-Wavenet-D",
        "cmn-CN-Standard-C",
        "cmn-CN-Standard-B",
        "cmn-CN-Standard-A",
        "cmn-CN-Standard-D",
    ],
    "cmn-TW": [
        "cmn-TW-Wavenet-A",
        "cmn-TW-Wavenet-B",
        "cmn-TW-Wavenet-C",
        "cmn-TW-Standard-A",
        "cmn-TW-Standard-B",
        "cmn-TW-Standard-C",
    ],
    "cs-CZ": ["cs-CZ-Wavenet-A", "cs-CZ-Standard-A"],
    "da-DK": [
        "da-DK-Wavenet-C",
        "da-DK-Wavenet-D",
        "da-DK-Wavenet-E",
        "da-DK-Wavenet-A",
        "da-DK-Standard-A",
        "da-DK-Standard-C",
        "da-DK-Standard-D",
        "da-DK-Standard-E",
    ],
    "de-DE": [
        "de-DE-Wavenet-F",
        "de-DE-Wavenet-A",
        "de-DE-Wavenet-B",
        "de-DE-Wavenet-C",
        "de-DE-Wavenet-D",
        "de-DE-Wavenet-E",
        "de-DE-Standard-E",
        "de-DE-Standard-A",
        "de-DE-Standard-B",
        "de-DE-Standard-C",
        "de-DE-Standard-D",
        "de-DE-Standard-F",
    ],
    "el-GR": ["el-GR-Wavenet-A", "el-GR-Standard-A"],
    "en-AU": [
        "en-AU-Wavenet-A",
        "en-AU-Wavenet-B",
        "en-AU-Wavenet-C",
        "en-AU-Wavenet-D",
        "en-AU-Standard-A",
        "en-AU-Standard-B",
        "en-AU-Standard-C",
        "en-AU-Standard-D",
    ],
    "en-GB": [
        "en-GB-Wavenet-A",
        "en-GB-Wavenet-B",
        "en-GB-Wavenet-C",
        "en-GB-Wavenet-D",
        "en-GB-Wavenet-F",
        "en-GB-Standard-A",
        "en-GB-Standard-B",
        "en-GB-Standard-C",
        "en-GB-Standard-D",
        "en-GB-Standard-F",
    ],
    "en-IN": [
        "en-IN-Wavenet-D",
        "en-IN-Wavenet-A",
        "en-IN-Wavenet-B",
        "en-IN-Wavenet-C",
        "en-IN-Standard-D",
        "en-IN-Standard-A",
        "en-IN-Standard-B",
        "en-IN-Standard-C",
    ],
    "en-US": [
        "en-US-Wavenet-G",
        "en-US-Wavenet-H",
        "en-US-Wavenet-I",
        "en-US-Wavenet-J",
        "en-US-Wavenet-A",
        "en-US-Wavenet-B",
        "en-US-Wavenet-C",
        "en-US-Wavenet-D",
        "en-US-Wavenet-E",
        "en-US-Wavenet-F",
        "en-US-Standard-A",
        "en-US-Standard-B",
        "en-US-Standard-C",
        "en-US-Standard-D",
        "en-US-Standard-E",
        "en-US-Standard-F",
        "en-US-Standard-G",
        "en-US-Standard-H",
        "en-US-Standard-I",
        "en-US-Standard-J",
    ],
    "es-ES": [
        "es-ES-Wavenet-C",
        "es-ES-Wavenet-D",
        "es-ES-Wavenet-B",
        "es-ES-Standard-C",
        "es-ES-Standard-D",
        "es-ES-Standard-B",
        "es-ES-Standard-A",
    ],
    "es-US": [
        "es-US-Wavenet-A",
        "es-US-Wavenet-B",
        "es-US-Wavenet-C",
        "es-US-Standard-A",
        "es-US-Standard-B",
        "es-US-Standard-C",
    ],
    "fi-FI": ["fi-FI-Wavenet-A", "fi-FI-Standard-A"],
    "fil-PH": [
        "fil-PH-Wavenet-A",
        "fil-PH-Wavenet-B",
        "fil-PH-Wavenet-C",
        "fil-PH-Wavenet-D",
        "fil-PH-Standard-B",
        "fil-PH-Standard-C",
        "fil-PH-Standard-D",
        "fil-PH-Standard-A",
    ],
    "fr-CA": [
        "fr-CA-Wavenet-A",
        "fr-CA-Wavenet-B",
        "fr-CA-Wavenet-C",
        "fr-CA-Wavenet-D",
        "fr-CA-Standard-A",
        "fr-CA-Standard-B",
        "fr-CA-Standard-C",
        "fr-CA-Standard-D",
    ],
    "fr-FR": [
        "fr-FR-Wavenet-E",
        "fr-FR-Wavenet-A",
        "fr-FR-Wavenet-B",
        "fr-FR-Wavenet-C",
        "fr-FR-Wavenet-D",
        "fr-FR-Standard-E",
        "fr-FR-Standard-A",
        "fr-FR-Standard-B",
        "fr-FR-Standard-C",
        "fr-FR-Standard-D",
    ],
    "gu-IN": [
        "gu-IN-Wavenet-A",
        "gu-IN-Wavenet-B",
        "gu-IN-Standard-A",
        "gu-IN-Standard-B",
    ],
    "hi-IN": [
        "hi-IN-Wavenet-D",
        "hi-IN-Wavenet-A",
        "hi-IN-Wavenet-B",
        "hi-IN-Wavenet-C",
        "hi-IN-Standard-D",
        "hi-IN-Standard-A",
        "hi-IN-Standard-B",
        "hi-IN-Standard-C",
    ],
    "hu-HU": ["hu-HU-Wavenet-A", "hu-HU-Standard-A"],
    "id-ID": [
        "id-ID-Wavenet-D",
        "id-ID-Wavenet-A",
        "id-ID-Wavenet-B",
        "id-ID-Wavenet-C",
        "id-ID-Standard-A",
        "id-ID-Standard-B",
        "id-ID-Standard-C",
        "id-ID-Standard-D",
    ],
    "is-IS": ["is-is-Standard-A"],
    "it-IT": [
        "it-IT-Wavenet-A",
        "it-IT-Wavenet-B",
        "it-IT-Wavenet-C",
        "it-IT-Wavenet-D",
        "it-IT-Standard-A",
        "it-IT-Standard-B",
        "it-IT-Standard-C",
        "it-IT-Standard-D",
    ],
    "ja-JP": [
        "ja-JP-Wavenet-B",
        "ja-JP-Wavenet-C",
        "ja-JP-Wavenet-D",
        "ja-JP-Wavenet-A",
        "ja-JP-Standard-A",
        "ja-JP-Standard-B",
        "ja-JP-Standard-C",
        "ja-JP-Standard-D",
    ],
    "kn-IN": [
        "kn-IN-Wavenet-A",
        "kn-IN-Wavenet-B",
        "kn-IN-Standard-A",
        "kn-IN-Standard-B",
    ],
    "ko-KR": [
        "ko-KR-Wavenet-A",
        "ko-KR-Wavenet-B",
        "ko-KR-Wavenet-C",
        "ko-KR-Wavenet-D",
        "ko-KR-Standard-B",
        "ko-KR-Standard-C",
        "ko-KR-Standard-D",
        "ko-KR-Standard-A",
    ],
    "lv-LV": ["lv-lv-Standard-A"],
    "ml-IN": [
        "ml-IN-Wavenet-A",
        "ml-IN-Wavenet-B",
        "ml-IN-Standard-A",
        "ml-IN-Standard-B",
    ],
    "ms-MY": [
        "ms-MY-Wavenet-A",
        "ms-MY-Wavenet-B",
        "ms-MY-Wavenet-C",
        "ms-MY-Wavenet-D",
        "ms-MY-Standard-A",
        "ms-MY-Standard-B",
        "ms-MY-Standard-C",
        "ms-MY-Standard-D",
    ],
    "nb-NO": [
        "nb-NO-Wavenet-A",
        "nb-NO-Wavenet-B",
        "nb-NO-Wavenet-C",
        "nb-NO-Wavenet-D",
        "nb-no-Wavenet-E",
        "nb-NO-Standard-A",
        "nb-NO-Standard-B",
        "nb-NO-Standard-C",
        "nb-NO-Standard-D",
        "nb-no-Standard-E",
        "nb-no-Standard-E",
    ],
    "nl-BE": [
        "nl-BE-Wavenet-A",
        "nl-BE-Wavenet-B",
        "nl-BE-Standard-A",
        "nl-BE-Standard-B",
    ],
    "nl-NL": [
        "nl-NL-Wavenet-B",
        "nl-NL-Wavenet-C",
        "nl-NL-Wavenet-D",
        "nl-NL-Wavenet-A",
        "nl-NL-Wavenet-E",
        "nl-NL-Standard-B",
        "nl-NL-Standard-C",
        "nl-NL-Standard-D",
        "nl-NL-Standard-E",
        "nl-NL-Standard-A",
    ],
    "pa-IN": [
        "pa-IN-Wavenet-A",
        "pa-IN-Wavenet-B",
        "pa-IN-Wavenet-C",
        "pa-IN-Wavenet-D",
        "pa-IN-Standard-A",
        "pa-IN-Standard-B",
        "pa-IN-Standard-C",
        "pa-IN-Standard-D",
    ],
    "pl-PL": [
        "pl-PL-Wavenet-A",
        "pl-PL-Wavenet-B",
        "pl-PL-Wavenet-C",
        "pl-PL-Wavenet-E",
        "pl-PL-Wavenet-D",
        "pl-PL-Standard-E",
        "pl-PL-Standard-A",
        "pl-PL-Standard-B",
        "pl-PL-Standard-C",
        "pl-PL-Standard-D",
    ],
    "pt-BR": ["pt-BR-Wavenet-A", "pt-BR-Standard-A"],
    "pt-PT": [
        "pt-PT-Wavenet-A",
        "pt-PT-Wavenet-B",
        "pt-PT-Wavenet-C",
        "pt-PT-Wavenet-D",
        "pt-PT-Standard-A",
        "pt-PT-Standard-B",
        "pt-PT-Standard-C",
        "pt-PT-Standard-D",
    ],
    "ro-RO": ["ro-RO-Standard-A", "ro-RO-Wavenet-A"],
    "ru-RU": [
        "ru-RU-Wavenet-E",
        "ru-RU-Wavenet-A",
        "ru-RU-Wavenet-B",
        "ru-RU-Wavenet-C",
        "ru-RU-Wavenet-D",
        "ru-RU-Standard-E",
        "ru-RU-Standard-A",
        "ru-RU-Standard-B",
        "ru-RU-Standard-C",
        "ru-RU-Standard-D",
    ],
    "sk-SK": ["sk-SK-Wavenet-A", "sk-SK-Standard-A"],
    "sr-RS": ["sr-rs-Standard-A"],
    "sv-SE": ["sv-SE-Wavenet-A", "sv-SE-Standard-A"],
    "ta-IN": [
        "ta-IN-Wavenet-A",
        "ta-IN-Wavenet-B",
        "ta-IN-Standard-A",
        "ta-IN-Standard-B",
    ],
    "te-IN": ["te-IN-Standard-A", "te-IN-Standard-B"],
    "th-TH": ["th-TH-Standard-A"],
    "tr-TR": [
        "tr-TR-Wavenet-B",
        "tr-TR-Wavenet-C",
        "tr-TR-Wavenet-D",
        "tr-TR-Wavenet-E",
        "tr-TR-Wavenet-A",
        "tr-TR-Standard-B",
        "tr-TR-Standard-C",
        "tr-TR-Standard-D",
        "tr-TR-Standard-E",
        "tr-TR-Standard-A",
    ],
    "uk-UA": ["uk-UA-Wavenet-A", "uk-UA-Standard-A"],
    "vi-VN": [
        "vi-VN-Wavenet-A",
        "vi-VN-Wavenet-B",
        "vi-VN-Wavenet-C",
        "vi-VN-Wavenet-D",
        "vi-VN-Standard-A",
        "vi-VN-Standard-B",
        "vi-VN-Standard-C",
        "vi-VN-Standard-D",
    ],
    "yue-HK": [
        "yue-HK-Standard-A",
        "yue-HK-Standard-B",
        "yue-HK-Standard-C",
        "yue-HK-Standard-D",
    ],
}


def get_language_code_of_voice(voice: str):
    # side note: language code still being needed in the api is kinda weird
    # especially considering the fact that voice name starts with the language code
    # but it's not my api so I can't do anything about it
    # mfw "google apis are industry standard"
    for language in language_voice_tree:
        if voice in language_voice_tree[language]:
            return language
