name: Deploy to Server

on: [push]

jobs:
  replace-live-image:
    runs-on: penguin-devops
    steps:
      - uses: actions/checkout@v4

      - name: Stop Old Container
        run: docker stop discord-tts || true

      - name: Remove Old Container
        run: docker rm discord-tts || true

      - name: Copy Required Files
        run: cp -r /home/beypazari/tts-files /actions-runner/discord-tts/_work/discord-tts/discord-tts/

      - name: Run New Image
        run: docker compose up -d