name: Deploy to Server

on: [push]

jobs:
  replace-live-image:
    runs-on: penguin-devops
    steps:
      - uses: actions/checkout@v4

      - name: Stop Old Container
        run: docker compose down || true

      - name: Remove Old Container
        run: docker rm discord-tts || true

      - name: Copy Required Files
        run: cp -r /home/beypazari/tts-files/* /actions-runner/discord-tts/_work/discord-tts/discord-tts/

      - name: Save Current Build Hash
        run: echo "$(git rev-parse --short HEAD)" >> build_hash.txt

      - name: Print Current Directory(debug)
        run: pwd

      - name: Print Files in Current Directory(debug)
        run: ls -l

      - name: Run New Image
        run: docker compose up --build -d